// src/app/blocks/portfolio-item/portfolio-item.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'portfolio-item',
  templateUrl: './portfolio-item.component.html',
  styleUrls: ['./portfolio-item.component.css']
})
export class PortfolioItemComponent {
  @Input() title:string = '';
  @Input() description:string = '';
  @Input() img:string = 'assets/img/shark.jpg';
  @Input() skillset:string[] = [];
}

<div class="portfolio-item">
    <div class="thumbnail">
        <img src="{{img}}" alt="">
    </div>
    <div class="main-content">
        <h2>{{title}}</h2>
        <p class="description" [innerHTML]="description"></p>
        <div class="skillset">
            <skill-chip
                *ngFor="let skill of skillset"
                name="{{skill}}"
            />
        </div>
    </div>
</div>

// src/blocks/PortfolioItem.tsx
import { ReactElement } from "react";
import SkillChip from "./SkillChip";

interface PortfolioItemProps {
    img?: string;
    title?: string;
    description?: ReactElement<any>;
    skillset?: string[];
}

export default function PortfolioItem({ img = "", title= "", description = <></>, skillset = [] }: PortfolioItemProps) {
    return (
        <div className="portfolio-item">
            <div className="thumbnail">
                <img src={img} alt=""/>
            </div>
            <div className="main-content">
                <h2>{title}</h2>
                <p className="description" dangerouslySetInnerHTML={{ __html: description }}></p>
                <div className="skillset">
                    {skillset.map(skill => <SkillChip skillName={skill} />)}
                    {/* <skill-chip
                        *ngFor="let skill of skillset"
                        name="{{skill}}"
                    /> */}
                </div>
            </div>
        </div>
    );
}
